---
name: Module-Util
version: 1.06
author:
  - 'Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>'
abstract: Module name tools and transformations
license: perl
requires:
  perl: 5.5.3
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Module::Util:
    file: lib/Module/Util.pm
    version: 1.06
resources:
  license: http://dev.perl.org/licenses/
