---
name: Module-Util
version: 1.01
author:
  - 'Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>'
abstract: Module name tools and transformations
license: perl
requires:
  perl: 5.5.3
recommends:
  File::Find::Rule: 0
build_requires:
  Test::More: 0
provides:
  Module::Util:
    file: lib/Module/Util.pm
    version: 1.01
generated_by: Module::Build version 0.2611
