---
abstract: 'Module name tools and transformations'
author:
  - 'Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Util
provides:
  Module::Util:
    file: lib/Module/Util.pm
    version: 1.08
requires:
  perl: v5.5.3
resources:
  license: http://dev.perl.org/licenses/
version: 1.08
